version: "3.8"

services:
  posgres:
    image: postgres:15
    container_name: duolingo-db
    restart: always
    environment:
      POSTGRES_USER: meg
      POSTGRES_PASSWORD: meg
      POSTGRES_DB: duolingo
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
